### ISSUE TITLE
Calling custom methods

### ISSUE THREAD

**Issue by nagu4u2c** [executeautomation/KatalonStudioWebUI#1]
Hi Karthik,

Liked your video series on Katalon Studio.

I have one question, can you tell me how can I create a method in one test case and call it in another test cases.

Regards,
Nagaraj

**Comment by executeautomation** [comment]
HI Nagaraj,

This you can do it via Katalon custom keywords option, which you can learn from here [https://www.youtube.com/watch?v=2zc2x1BcRMo](url)

Thanks,
Karthik KK
